Adding PHY to K64F
renode/renode pull request #147
Opened 2020-11-03 09:01 UTC by jensschroer

Adding the IRQ for the PHY interface and the PHY component to the K64F platform file.

This PR is depending on https://github.com/renode/renode-infrastructure/pull/20 .

2020-11-05 11:28 UTC, PiotrZierhoffer requested changes
Can you please change the commit message?

```
[GH#147] Add PHY to K64F
```

2020-11-11 13:49 UTC, jensschroer commented
Changed the commit message. Just waiting for the merge so that I can update the submodule.

2020-11-12 23:20 UTC, PiotrZierhoffer approved these changes

2020-11-12 23:21 UTC, merged

2020-11-12 23:21 UTC, PiotrZierhoffer commented
I allowed myself to bump it on your branch. It is now merged, thanks for your contribution!

2020-11-13 02:35 UTC, hakehuang commented
thanks all @PiotrZierhoffer , @jensschroer